--!strict

--[=[
	@class Observers

	A collection of observer utility functions.
]=]

return {
	ObserveTag = require(script.observeTag),
	ObserveAttribute = require(script.observeAttribute),
	ObserveProperty = require(script.observeProperty),
	ObservePlayer = require(script.observePlayer),
	ObserveCharacter = require(script.observeCharacter),
	ObserveLocalCharacter = require(script.observeLocalCharacter),
}
